filter-set-list:
  - grades: C,D,E,HR
    employment_length_over: 3
    inquiries_under: 0
    delinquencies_under: 0
    payment_income_ratio_under: 0.10
    loan_count_over: 0
  - grades: C,D,E,HR
    employment_length_over: 2
    inquiries_under: 0
    delinquencies_under: 0
    payment_income_ratio_under: 0.11
    loan_count_over: 4
  - grades: B,C,D,E
    employment_length_over: 0
    inquiries_under: 1
    delinquencies_under: 1
    payment_income_ratio_under: 0.12
    loan_count_over: 8
  - grades: AA,A,B,C,D,E
    employment_length_over: 0
    inquiries_under: 2
    delinquencies_under: 2
    payment_income_ratio_under: 0.13
    loan_count_over: 12
